### ISSUE TITLE
Namespaced keywords are not supported

### ISSUE THREAD

**Issue by kennyjwilli** [weavejester/cljfmt#106]
Parsing the below string using rewrite-cljs or rewrite-clj works as expected:
```clojure
(rewrite-clj.node/string
  (rewrite-clj.parser/parse-string-all "(ns myns.core)\n\n{::foo-bar (do (map)\n               (foo))}"))
=> "(ns myns.core)\n\n{::foo-bar (do (map)\n               (foo))}"
```

Using cljfmt throws this exception:
```clojure
(cljfmt.core/reformat-string "(ns myns.core)\n\n{::foo-bar (do (map)\n               (foo))}")
repl:13
throw e__9355__auto__;
^
Error: Namespaced keywords not supported !
    at rewrite_clj.node.keyword.KeywordNode.rewrite_clj$node$protocols$Node$sexpr$arity$1 (/home/kenny/compute_software/cljfmt-cli/.cljs_node_repl/rewrite_clj/node/keyword.js:149:8)
    at rewrite_clj$node$protocols$sexpr (/home/kenny/compute_software/cljfmt-cli/.cljs_node_repl/rewrite_clj/node/protocols.js:62:10)
    at rewrite_clj$zip$base$sexpr (/home/kenny/compute_software/cljfmt-cli/.cljs_node_repl/rewrite_clj/zip/base.js:57:31)
    at cljfmt$core$token_value (/home/kenny/compute_software/cljfmt-cli/.cljs_node_repl/cljfmt/core.js:318:30)
    at cljfmt$core$form_symbol (/home/kenny/compute_software/cljfmt-cli/.cljs_node_repl/cljfmt/core.js:332:71)
    at /home/kenny/compute_software/cljfmt-cli/.cljs_node_repl/cljfmt/core.js:339:131
    at cljfmt$core$inner_indent (/home/kenny/compute_software/cljfmt-cli/.cljs_node_repl/cljfmt/core.js:350:3)
    at cljs.core._add_method.call.vec__15752 (/home/kenny/compute_software/cljfmt-cli/.cljs_node_repl/cljfmt/core.js:441:33)
    at Function.cljs.core.some_fn.cljs$core$IFn$_invoke$arity$2.cljs$core$sp2__1 [as cljs$core$IFn$_invoke$arity$1] (/home/kenny/compute_software/cljfmt-cli/out/.cljs_node_repl/cljs/core.js:16820:85)
    at /home/kenny/compute_software/cljfmt-cli/out/.cljs_node_repl/cljs/core.js:17121:75
```

**Comment by weavejester** [comment]
What does your dependency tree look like? Are you pulling in an older version of rewrite-clj?

**Comment by kennyjwilli** [comment]
```
[org.clojure/clojure "1.8.0"]
[org.clojure/clojurescript "1.9.946"]
[rewrite-cljs "0.4.4"]
[cljfmt "0.5.7" :exclusions [rewrite-cljs]]
```
Newer version of rewrite-cljs.

**Comment by weavejester** [comment]
It looks like it's an omission in rewrite-cljs; even the latest master branch has the check: https://github.com/rundis/rewrite-cljs/blob/master/src/rewrite_clj/node/keyword.cljs#L16

**Comment by kennyjwilli** [comment]
Then why would running the above code with rewrite-cljs format correctly?

**Comment by weavejester** [comment]
It appears that only the `rewrite-clj.node/sexpr` function doesn't work, and this is used internally by the zipper.

**Comment by philomates** [comment]
I'm also encountering some issues with namespaced keywords
Running cljfmt on this code:
```clojure
(println (not (= ::result/foo 2)))
```
results in the `::result/foo` getting turned into `:result/foo` (without the double `:`)
```
Replacing
  (not (= :result/foo 2))
 with
  (not= :result/foo 2)
```

I'm on `cljfmt 0.6.1`

**Comment by conan** [comment]
Has anyone found a way around this? It broadly seems to make it impossible to format files in a codebase that uses namespaced keywords.

**Comment by lread** [comment]
This should be fixed by an [upgrade to rewrite-clj v1](https://github.com/weavejester/cljfmt/issues/211).
