### ISSUE TITLE
Build error with ClojureScript 1.10.866, works with 1.11.4

### ISSUE THREAD

**Issue by or** [weavejester/cljfmt#262]
On the current master: `lein clean; lein uberjar` results in this error:
```
Syntax error compiling at (cljfmt/test_util/common.cljc:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7652)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at cljfmt.test_util.cljs$eval1266$loading__6737__auto____1267.invoke(cljs.cljc:1)
	at cljfmt.test_util.cljs$eval1266.invokeStatic(cljs.cljc:1)
	at cljfmt.test_util.cljs$eval1266.invoke(cljs.cljc:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7170)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cljs.analyzer$ns_side_effects$fn__2802.invoke(analyzer.cljc:4115)
	at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:4114)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:4086)
	at cljs.analyzer$parse_ns$fn__2891$fn__2895.invoke(analyzer.cljc:4414)
	at cljs.analyzer$parse_ns$fn__2891.invoke(analyzer.cljc:4413)
	at cljs.analyzer$parse_ns.invokeStatic(analyzer.cljc:4372)
	at cljs.analyzer$parse_ns.invoke(analyzer.cljc:4351)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$memoize$fn__6894.doInvoke(core.clj:6342)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at cljs.analyzer$parse_ns.invokeStatic(analyzer.cljc:4362)
	at cljs.analyzer$parse_ns.invoke(analyzer.cljc:4351)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$memoize$fn__6894.doInvoke(core.clj:6342)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cljs.compiler$find_source.invokeStatic(compiler.cljc:1810)
	at cljs.compiler$find_source.invoke(compiler.cljc:1809)
	at clojure.core$map$fn__5884.invoke(core.clj:2759)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:713)
	at clojure.core$next__5403.invokeStatic(core.clj:64)
	at clojure.core$reduce1.invokeStatic(core.clj:946)
	at clojure.core$set.invokeStatic(core.clj:4101)
	at clojure.core$set.invoke(core.clj:4093)
	at cljs.closure$add_dependency_sources.invokeStatic(closure.clj:1021)
	at cljs.closure$add_dependency_sources.invoke(closure.clj:1013)
	at cljs.closure$build$fn__6347.invoke(closure.clj:3157)
	at cljs.closure$build.invokeStatic(closure.clj:3153)
	at cljs.closure$build.invoke(closure.clj:3065)
	at cljs.build.api$build.invokeStatic(api.clj:231)
	at cljs.build.api$build.invoke(api.clj:212)
	at cljs.build.api$build.invokeStatic(api.clj:218)
	at cljs.build.api$build.invoke(api.clj:212)
	at cljsbuild.compiler$compile_cljs$fn__707.invoke(compiler.clj:61)
	at cljsbuild.compiler$compile_cljs.invokeStatic(compiler.clj:60)
	at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:48)
	at cljsbuild.compiler$run_compiler.invokeStatic(compiler.clj:168)
	at cljsbuild.compiler$run_compiler.invoke(compiler.clj:129)
	at user$eval836$iter__884__888$fn__889$fn__915.invoke(843433f8f8e8bf4f5d91588a1a5dfa57128d2f80-init.clj:1)
	at user$eval836$iter__884__888$fn__889.invoke(843433f8f8e8bf4f5d91588a1a5dfa57128d2f80-init.clj:1)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$dorun.invokeStatic(core.clj:3121)
	at clojure.core$doall.invokeStatic(core.clj:3136)
	at clojure.core$doall.invoke(core.clj:3136)
	at user$eval836.invokeStatic(843433f8f8e8bf4f5d91588a1a5dfa57128d2f80-init.clj:1)
	at user$eval836.invoke(843433f8f8e8bf4f5d91588a1a5dfa57128d2f80-init.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7171)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	at clojure.lang.Compiler.loadFile(Compiler.java:7578)
	at clojure.main$load_script.invokeStatic(main.clj:475)
	at clojure.main$init_opt.invokeStatic(main.clj:477)
	at clojure.main$init_opt.invoke(main.clj:477)
	at clojure.main$initialize.invokeStatic(main.clj:508)
	at clojure.main$null_opt.invokeStatic(main.clj:542)
	at clojure.main$null_opt.invoke(main.clj:539)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
Caused by: java.lang.IllegalAccessError: reformat-string does not exist
	at clojure.core$refer.invokeStatic(core.clj:4237)
	at clojure.core$refer.doInvoke(core.clj:4205)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_lib.invokeStatic(core.clj:5955)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at cljfmt.test_util.common$eval1272$loading__6737__auto____1273.invoke(common.cljc:1)
	at cljfmt.test_util.common$eval1272.invokeStatic(common.cljc:1)
	at cljfmt.test_util.common$eval1272.invoke(common.cljc:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7170)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	... 120 more
Uberjar aborting because jar failed: Subprocess failed (exit code: 1)
```

I can't figure out what the problem is. Do you (or anyone else) see this?
If I upgrade the ClojureScript dependency to 1.11.4, then all works as expected. My Google fu wasn't enough to find any similar issues.

While working on my other PRs I just kept local commits that upgrade Clojure and ClojureScript dependencies. If you are ok with it, then I can prepare a PR for this. Perhaps also upgrade the other dependencies and verify there are no breaking changes.

**Comment by or** [comment]
https://github.com/weavejester/cljfmt/issues/236 might have the same root cause, the errors are not identical but similar.
