### ISSUE TITLE
latest 0.11.0 linux static binary is broken

### ISSUE THREAD

**Issue by sg-qwt** [weavejester/cljfmt#313]
version: cljfmt-0.11.0-linux-amd64-static.tar.gz

> ./cljfmt 
Exception in thread "main" java.lang.NullPointerException
        at cljfmt.config$directory_QMARK_.invokeStatic(config.clj:53)
        at cljfmt.config$load_config.invokeStatic(config.clj:61)
        at cljfmt.main$_main.invokeStatic(main.clj:85)
        at cljfmt.main$_main.doInvoke(main.clj:85)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at cljfmt.main.main(Unknown Source)

0.10.6 was fine

I think it's introduced by the --config cli change, unfortunately I'm not familiar with graalvm..

**Comment by weavejester** [comment]
D'oh! It looks like the tests didn't account for no config file, as there's a config in the base project directory it always finds. Let me fix that real quick...

**Comment by weavejester** [comment]
That's the plan! Stand by.

**Comment by weavejester** [comment]
Released 0.11.1. Apologies for the bug!
